### ISSUE TITLE
일부 저장소를 내려받을 수 없습니다.

### ISSUE THREAD

**Issue by ghost** [taeminhong/sysadmin#1]
저장소를 내려받거나 이미 내려받은 저장소를 업데이트하려고 하면 다음과 같은 에러메시지와 함께 동작이 실패합니다.

```
Unable to connect to a repository at URL 'svn://dev.kovi.com/SIT/trunk'
예상되는 파일시스템 포맷 '2', 발견된 포맷 '7'
```

문제가 발생하는 저장소 목록입니다.
- KT_CellTREK_Commander
- KVLED
- Design
- LED
- Design
- NewProject
- RnA
- SIT
- TestEclipse
- TestSVN
- uffia

이 현상은 7월 28일부터 발생했으며 이전에는 문제가 없었습니다.

**Comment by ghost** [comment]
27일 새벽에 정전으로 서버 전원이 내려갔습니다.
이 현상과 관련이 있는지는 아직 밝혀지지 않았습니다.

**Comment by ghost** [comment]
에러 메시지가 뜻하는 바대로 문제가 발생한 저장소는 모두 Filesystem Format이 7이며 나머지는 2입니다.
Filesystem Format은 저장소의 db/format 파일을 열어보거나 svnadmin info로 확인할 수 있습니다.
[파일 시스템 7](https://subversion.apache.org/docs/release-notes/1.9.html)은 서브버전 1.9에서 도입한 새로운 파일 시스템이며 서버에서 사용하는 버전은 1.9.4입니다.

**Comment by ghost** [comment]
문제가 되는 저장소를 다른 시스템에 옮겨서 테스트 해봤으나 현상을 재현할 수 없었습니다.
정확한 이유는 파악하지 못했으나 정전이 시스템에 영향을 미친것으로 보입니다.

**Comment by ghost** [comment]
서브버전 1.4와 호환되는 RnA와 SIT 저장소 클론을 만들었습니다.
주소는 각각 RnA-1.4compatible과 SIT-1.4compatible입니다.
프로젝트 참여자는 위 주소로 저장소를 새로 내려받고 작업 내열을 그곳에 덮어써서 커밋하셔야합니다.

**Comment by taeminhong** [comment]
시스템에 2개의 svnserve 가 설치되어있습니다.
하나는 E:/KoviProjectSystem/subversion/bin/에, 다른 하나는 C:/Program Files/CollabNet/Subversion Client/에 있으며 버전은 각기 1.4.6과 1.9.4입니다.
1.4.6 버전으로 서버를 구동하고 SIT 저장소를 내려받으려고 하면 에러가 발생하고 1.9.4 버전으로 구동하면 문제가 발생하지 않습니다.

지금은 1.9.4 버전으로 서비스를 구동하기 때문에 저장소를 만들 때 더는 --pre-1.5-compatible 옵션을 줄 필요는 없습니다.
