### ISSUE TITLE
svn 계정 신청 합니다.

### ISSUE THREAD

**Issue by childmild** [taeminhong/sysadmin#9]
코비하우스 상진씨 svn 계정 등록을 위해  svn 계정 신청합니다.

신규 생성 및 신청 계정 : sangjin916

기존 계정 신청 계정 : childmild

저장소 주소 :  svn://dev.kovi.com/KOVIHouse_Solution/House_Solution

개발도구 : 안드로이드 스튜디오

**Comment by taeminhong** [comment]
계정 생성했습니다.
